package com.drawgraph.graphics;

import com.drawgraph.model.Graph;
import com.drawgraph.model.LayeredPositionedGraph;
import com.drawgraph.model.Node;
import com.drawgraph.parser.GraphMLParser;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.xml.sax.SAXException;

import java.awt.*;
import java.io.IOException;
import javax.swing.*;
import javax.xml.parsers.ParserConfigurationException;

/**
 * Date: Oct 24, 2010
 * Time: 11:31:07 AM
 *
 * @author denisk
 */
public class DrawGraphUI {

	private JList chooseFileList;
	//	private JSplitPane verticalSplit;
	private JScrollPane chooseFileScrollPanel;
	private JPanel rootPanel;
	private JPanel mainPanel;
	private JPanel tweakPanel;
	private JButton directoryChooseButton;
	private JRadioButton barycenterRadioButton;
	private JRadioButton medianRadioButton;
	private JSlider layerLengthSlider;
	private JPanel canvasPanel;

	private LayeredPositionedGraph layeredPositionedGraph;
	private SimpleGraphDrawer drawer;


	public static void main(String[] args) throws IOException, SAXException, ParserConfigurationException {
		Toolkit toolkit = Toolkit.getDefaultToolkit();
		Dimension screenSize = toolkit.getScreenSize();

		double screenWidth = screenSize.getWidth();
		double screenHeight = screenSize.getHeight();
		JFrame frame = new JFrame("DrawGraphUI");
		DrawGraphUI ui = new DrawGraphUI();
		frame.setContentPane(ui.rootPanel);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.pack();
		frame.setSize(800, 600);

		ui.initComponents();
		//	ui.simpleDraw();
		frame.setLocation((int) screenWidth / 2 - frame.getWidth() / 2, (int) screenHeight / 2 - frame.getHeight() / 2);
		frame.setVisible(true);
	}

	private LayeredPositionedGraph parseGraph() throws IOException, SAXException, ParserConfigurationException {
		GraphMLParser parser = new GraphMLParser();
		Graph<Node> graph = parser.buildGraph("/media/Windows_data/work/swisslabs/g.57.26.graphml");

		GraphScaler scaler = new GraphScalerImpl();
		scaler.setLayerOffset(70);
		scaler.setLeftOffset(30);
		scaler.setMinDistance(350);
		scaler.setTopOffset(30);
		LayeredPositionedGraph layeredPositionedGraph = scaler.scale(graph, new SimpleLayeredGraphOrder(3));
		layeredPositionedGraph.setRadius(15);

		return layeredPositionedGraph;
	}

	private void initComponents() throws IOException, SAXException, ParserConfigurationException {
		DefaultListModel listModel = new DefaultListModel();
		listModel.addElement("Hello!");
		listModel.addElement("World!");
		chooseFileList.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
		chooseFileList.setSelectedIndex(0);
		chooseFileList.setModel(listModel);
		layeredPositionedGraph = parseGraph();
		drawer = new SimpleGraphDrawer();

	}


	private void createUIComponents() {
		canvasPanel = new JPanel() {
			@Override
			protected void paintComponent(Graphics g) {
				super.paintComponent(g);
				Graphics2D g2 = (Graphics2D) g;
				drawer.drawGraph(layeredPositionedGraph, g2);

				setPreferredSize(new Dimension(layeredPositionedGraph.getWidth(), layeredPositionedGraph.getHeight()));
				revalidate();
			}
		};
	}

	{
		// GUI initializer generated by IntelliJ IDEA GUI Designer
		// >>> IMPORTANT!! <<<
		// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		createUIComponents();
		rootPanel = new JPanel();
		rootPanel
				.setLayout(new FormLayout("center:d:grow,left:4dlu:noGrow,center:210px:grow,left:d:grow", "center:45px:noGrow,top:8px:noGrow,center:d:grow"));
		mainPanel = new JPanel();
		mainPanel.setLayout(new FormLayout("center:150px:noGrow,center:d:grow", "center:d:grow"));
		CellConstraints cc = new CellConstraints();
		rootPanel.add(mainPanel, cc.xyw(1, 3, 4, CellConstraints.FILL, CellConstraints.FILL));
		chooseFileScrollPanel = new JScrollPane();
		mainPanel.add(chooseFileScrollPanel, cc.xy(1, 1, CellConstraints.FILL, CellConstraints.FILL));
		chooseFileList = new JList();
		chooseFileScrollPanel.setViewportView(chooseFileList);
		final JScrollPane scrollPane1 = new JScrollPane();
		mainPanel.add(scrollPane1, cc.xy(2, 1, CellConstraints.FILL, CellConstraints.FILL));
		canvasPanel.setBackground(new Color(-52378));
		scrollPane1.setViewportView(canvasPanel);
		tweakPanel = new JPanel();
		tweakPanel
				.setLayout(new FormLayout("fill:d:noGrow,fill:60px:noGrow,left:4dlu:noGrow,fill:185px:noGrow,left:4dlu:noGrow,fill:185px:noGrow,left:4dlu:noGrow,fill:80px:noGrow,left:4dlu:noGrow,fill:d:grow", "center:35px:noGrow"));
		tweakPanel.setBackground(new Color(-3342388));
		rootPanel.add(tweakPanel, cc.xyw(1, 1, 4, CellConstraints.FILL, CellConstraints.FILL));
		tweakPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLoweredBevelBorder(), null));
		final JPanel panel1 = new JPanel();
		panel1.setLayout(new FormLayout("fill:60px:noGrow,left:4dlu:noGrow,fill:185px:noGrow,left:4dlu:noGrow,fill:185px:noGrow,left:4dlu:noGrow,fill:80px:noGrow,left:4dlu:noGrow,fill:d:grow", "center:35px:noGrow"));
		panel1.setBackground(new Color(-3355393));
		tweakPanel.add(panel1, cc.xyw(2, 1, 9, CellConstraints.DEFAULT, CellConstraints.FILL));
		directoryChooseButton = new JButton();
		directoryChooseButton.setText("Folder");
		panel1.add(directoryChooseButton, cc.xy(1, 1));
		barycenterRadioButton = new JRadioButton();
		barycenterRadioButton.setText("Barycenter");
		panel1.add(barycenterRadioButton, cc.xy(3, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		medianRadioButton = new JRadioButton();
		medianRadioButton.setText("Median");
		panel1.add(medianRadioButton, cc.xy(5, 1));
		layerLengthSlider = new JSlider();
		panel1.add(layerLengthSlider, cc.xy(9, 1, CellConstraints.FILL, CellConstraints.DEFAULT));
		final JLabel label1 = new JLabel();
		label1.setText("Layer length:");
		panel1.add(label1, cc.xy(7, 1));
		ButtonGroup buttonGroup;
		buttonGroup = new ButtonGroup();
		buttonGroup.add(barycenterRadioButton);
		buttonGroup.add(medianRadioButton);
	}

	/** @noinspection ALL */
	public JComponent $$$getRootComponent$$$() {
		return rootPanel;
	}
}
